"""
LoRA Config Generator for ai-toolkit

Generates a ready-to-run YAML config file for ai-toolkit SDXL LoRA training.
Automatically adjusts settings based on available VRAM.

Usage:
    python tools/generate_lora_config.py tiki-bar-interior
    python tools/generate_lora_config.py beach-sunset --vram 12 --steps 3000
    python tools/generate_lora_config.py artist-john --trigger "ohwx" --type character --vram 8

Outputs: config/loras/<name>.yaml ready for: python run.py config/loras/<name>.yaml
"""

import argparse
import sys
from pathlib import Path

# VRAM profiles: settings tuned for specific VRAM amounts
VRAM_PROFILES = {
    8: {
        "batch_size": 1,
        "gradient_accumulation_steps": 2,
        "gradient_checkpointing": True,
        "optimizer": "adamw8bit",
        "train_text_encoder": False,
        "cache_latents_to_disk": True,
        "network_rank": 8,
        "resolution": 1024,
        "dtype": "fp16",
        "note": "8GB VRAM (tight but works)",
    },
    12: {
        "batch_size": 1,
        "gradient_accumulation_steps": 1,
        "gradient_checkpointing": True,
        "optimizer": "adamw8bit",
        "train_text_encoder": False,
        "cache_latents_to_disk": True,
        "network_rank": 16,
        "resolution": 1024,
        "dtype": "bf16",
        "note": "12GB VRAM (comfortable)",
    },
    16: {
        "batch_size": 2,
        "gradient_accumulation_steps": 1,
        "gradient_checkpointing": True,
        "optimizer": "adamw8bit",
        "train_text_encoder": False,
        "cache_latents_to_disk": False,
        "network_rank": 16,
        "resolution": 1024,
        "dtype": "bf16",
        "note": "16GB VRAM (good headroom)",
    },
    24: {
        "batch_size": 4,
        "gradient_accumulation_steps": 1,
        "gradient_checkpointing": False,
        "optimizer": "adamw",
        "train_text_encoder": True,
        "cache_latents_to_disk": False,
        "network_rank": 32,
        "resolution": 1024,
        "dtype": "bf16",
        "note": "24GB VRAM (full quality)",
    },
}

# Training presets by LoRA type
LORA_TYPE_PRESETS = {
    "style": {
        "steps": 2000,
        "lr": 1e-4,
        "caption_dropout_rate": 0.1,
        "description": "Visual style (lighting, color grading, film look)",
        "sample_prompts": [
            "a beautiful tropical beach at sunset, {trigger}",
            "a cozy bar interior with warm lighting, {trigger}",
            "a person standing on a boat deck, ocean view, {trigger}",
        ],
    },
    "scene": {
        "steps": 2500,
        "lr": 1e-4,
        "caption_dropout_rate": 0.05,
        "description": "Specific scene type (tiki bar, beach bonfire, etc.)",
        "sample_prompts": [
            "a detailed photograph, {trigger}, high quality",
            "{trigger}, cinematic lighting, professional photography",
            "{trigger}, wide angle shot, vivid colors",
        ],
    },
    "character": {
        "steps": 1500,
        "lr": 5e-5,
        "caption_dropout_rate": 0.0,
        "description": "Person/character identity (artist, performer)",
        "sample_prompts": [
            "a portrait photo of {trigger}, looking at camera",
            "a photo of {trigger} performing on stage with a guitar",
            "a photo of {trigger} on the beach, casual clothing",
        ],
    },
}


def generate_config(
    name: str,
    dataset_dir: Path,
    output_dir: Path,
    vram_gb: int,
    lora_type: str,
    trigger_word: str,
    steps: int = 0,
    lr: float = 0.0,
    base_model: str = "stabilityai/stable-diffusion-xl-base-1.0",
) -> str:
    """Generate a YAML config string for ai-toolkit."""

    # Get profiles
    vram_key = min(VRAM_PROFILES.keys(), key=lambda k: abs(k - vram_gb))
    vram = VRAM_PROFILES[vram_key]
    preset = LORA_TYPE_PRESETS[lora_type]

    # Allow overrides
    final_steps = steps if steps > 0 else preset["steps"]
    final_lr = lr if lr > 0 else preset["lr"]

    # Format sample prompts with trigger word
    sample_prompts = []
    for p in preset["sample_prompts"]:
        formatted = p.replace("{trigger}", trigger_word if trigger_word else name)
        sample_prompts.append(f'          - "{formatted}"')
    prompts_yaml = "\n".join(sample_prompts)

    config = f"""---
# BeatCanvas LoRA Training Config
# Name: {name}
# Type: {lora_type} - {preset['description']}
# VRAM: {vram['note']}
# Generated by: tools/generate_lora_config.py
#
# Run with: python run.py config/loras/{name}.yaml
# Training will run unattended to completion.

job: extension
config:
  name: "{name}"
  process:
    - type: "sd_trainer"
      training_folder: "{output_dir / name}"
      device: cuda:0
      performance_log_every: 500

      network:
        type: "lora"
        linear: {vram['network_rank']}
        linear_alpha: {vram['network_rank']}

      save:
        dtype: float16
        save_every: {max(final_steps // 4, 250)}
        max_step_saves_to_keep: 3

      datasets:
        - folder_path: "{dataset_dir}"
          caption_ext: ".txt"
          caption_dropout_rate: {preset['caption_dropout_rate']}
          resolution: {vram['resolution']}
          default_caption: ""
          is_regularization: false
          cache_latents_to_disk: {str(vram['cache_latents_to_disk']).lower()}

      train:
        batch_size: {vram['batch_size']}
        steps: {final_steps}
        gradient_accumulation_steps: {vram['gradient_accumulation_steps']}
        train_unet: true
        train_text_encoder: {str(vram['train_text_encoder']).lower()}
        gradient_checkpointing: {str(vram['gradient_checkpointing']).lower()}
        noise_scheduler: "ddpm"
        optimizer: "{vram['optimizer']}"
        lr: {final_lr}
        dtype: {vram['dtype']}
        skip_first_sample: true
        disable_sampling: false
        lr_scheduler: "constant_with_warmup"
        lr_warmup_steps: {min(100, final_steps // 10)}
        min_snr_gamma: 5.0

      model:
        name_or_path: "{base_model}"
        is_v2: false
        is_v_pred: false
        is_xl: true

      sample:
        sampler: "ddpm"
        sample_every: {max(final_steps // 4, 250)}
        width: 1024
        height: 1024
        prompts:
{prompts_yaml}
        neg: "blurry, low quality, distorted, deformed, ugly"
        seed: 42
        walk_seed: true
        guidance_scale: 7
        sample_steps: 20

meta:
  name: "{name}"
  version: "1.0.0"
"""
    return config


def main():
    parser = argparse.ArgumentParser(
        description="Generate ai-toolkit YAML config for LoRA training"
    )
    parser.add_argument("name", help="LoRA name (e.g., 'tiki-bar-interior')")
    parser.add_argument(
        "--dataset",
        type=str,
        default=None,
        help="Dataset directory (default: datasets/<name>/)",
    )
    parser.add_argument(
        "--vram",
        type=int,
        default=12,
        choices=[8, 12, 16, 24],
        help="Available VRAM in GB (default: 12)",
    )
    parser.add_argument(
        "--type",
        dest="lora_type",
        choices=["style", "scene", "character"],
        default="scene",
        help="LoRA type: style, scene, or character (default: scene)",
    )
    parser.add_argument(
        "--trigger",
        type=str,
        default="",
        help="Trigger word (default: uses LoRA name)",
    )
    parser.add_argument(
        "--steps",
        type=int,
        default=0,
        help="Training steps (default: auto from type preset)",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=0.0,
        help="Learning rate (default: auto from type preset)",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="stabilityai/stable-diffusion-xl-base-1.0",
        help="Base model (default: SDXL 1.0)",
    )

    args = parser.parse_args()

    # Resolve paths
    dataset_dir = Path(args.dataset) if args.dataset else Path("datasets") / args.name
    config_dir = Path("config") / "loras"
    output_dir = Path("output") / "loras"
    config_path = config_dir / f"{args.name}.yaml"

    if not dataset_dir.exists():
        print(f"WARNING: Dataset directory does not exist yet: {dataset_dir}")
        print("  Run pexels_collector.py first to create it.")
        print("  Generating config anyway...")
        print()

    # Generate config
    config_dir.mkdir(parents=True, exist_ok=True)
    config_content = generate_config(
        name=args.name,
        dataset_dir=dataset_dir,
        output_dir=output_dir,
        vram_gb=args.vram,
        lora_type=args.lora_type,
        trigger_word=args.trigger or args.name,
        steps=args.steps,
        lr=args.lr,
        base_model=args.model,
    )

    config_path.write_text(config_content, encoding="utf-8")
    print(f"Config written: {config_path}")
    print()
    print(f"  LoRA type:   {args.lora_type}")
    print(f"  VRAM target: {args.vram}GB")
    print(f"  Dataset:     {dataset_dir}")
    print(f"  Trigger:     {args.trigger or args.name}")
    print()
    print(f"To train: cd ai-toolkit && python run.py ../{config_path}")


if __name__ == "__main__":
    main()
